### ISSUE TITLE
Can not work in IE10 and Safari, just due to ics.js?

### ISSUE THREAD

**Issue by JimmyLv** [jshor/angular-addtocalendar#4]

**Comment by jshor** [comment]
Correct, angular-addtocalendar will not work in Safari ≤ 6 or IE ≤ 9 because ics.js relies on FIleSaver.js which doesn't work in those browsers.

**Comment by JimmyLv** [comment]
@jshor But my IE is version 10, Safari is Version 9... do you know another way about how to support these browsers? thanks!

**Comment by jshor** [comment]
What happens on IE10? When you click "iCalendar" nothing happens?

**Comment by JimmyLv** [comment]
yes, you are right, maybe due to fileSave.js not work as expected.

**Comment by jshor** [comment]
Yes I see, in Safari it seems to open a new blank tab. I've also noticed problems with bower.json so maybe we should consider an alternative to FileSaver.js/ics.js.

**Comment by jshor** [comment]
This is now fixed in v0.0.7.

**Comment by JimmyLv** [comment]
@jshor Thanks for your fix. But still not as my expected which can be download directly in Safari and the file will be opened by native Calendar application. Just like the button in the website -> <www.addtocalendar.com>
